# Generated by Django 5.2 on 2025-04-22 02:06

import apps.processor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_folder', models.CharField(max_length=255)),
                ('master_file', models.FileField(upload_to=apps.processor.models.upload_to)),
                ('titles_file', models.FileField(upload_to=apps.processor.models.upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
