# Generated by Django 5.2 on 2025-04-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedfile',
            name='titles_file',
        ),
        migrations.RemoveField(
            model_name='processedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='processedfile',
            name='summary_file',
            field=models.FileField(blank=True, null=True, upload_to='summary/'),
        ),
        migrations.AlterField(
            model_name='processedfile',
            name='master_file',
            field=models.FileField(upload_to='processed/'),
        ),
    ]
